In [1]:
import pandas as pd
import numpy as np

In [2]:
df_err = pd.read_csv('reports/fmriprep_error_report_ALL.csv')

In [3]:
df_err['category'].value_counts()

category
Unclassified error               1113
Nipype node crash                 411
Inputs: session has no BOLD       322
TemplateFlow cache/bind issue       2
Resources: Out of memory            1
Name: count, dtype: int64

In [4]:
df_err.shape

(1849, 6)

In [8]:
df_err.drop_duplicates(subset='file')

,source,file,subject,session,category,detail
0,log,/N/project/statadni/20250922_Saige/fmriprep/re...,NaN,NaN,Unclassified error,"INFO: fuse2fs not found, will not be able t..."
1,log,/N/project/statadni/20250922_Saige/fmriprep/re...,NaN,NaN,Nipype node crash,Traceback (most recent call last):
2,log,/N/project/statadni/20250922_Saige/fmriprep/re...,sub-ADNI002S0413,ses-M060,Unclassified error,fMRIPrep failed for sub-ADNI002S0413 with exit...
3,log,/N/project/statadni/20250922_Saige/fmriprep/re...,NaN,NaN,Unclassified error,"INFO: fuse2fs not found, will not be able t..."
4,log,/N/project/statadni/20250922_Saige/fmriprep/re...,NaN,NaN,Unclassified error,"INFO: fuse2fs not found, will not be able t..."
...,...,...,...,...,...,...
1844,log,/N/project/statadni/20250922_Saige/fmriprep/re...,NaN,NaN,Unclassified error,"INFO: fuse2fs not found, will not be able t..."
1845,log,/N/project/statadni/20250922_Saige/fmriprep/re...,NaN,NaN,Unclassified error,"INFO: fuse2fs not found, will not be able t..."
1846,log,/N/project/statadni/20250922_Saige/fmriprep/re...,NaN,NaN,Unclassified error,"INFO: fuse2fs not found, will not be able t..."
1847,log,/N/project/statadni/20250922_Saige/fmriprep/re...,NaN,NaN,Unclassified error,"INFO: fuse2fs not found, will not be able t..."
1848,log,/N/project/statadni/20250922_Saige/fmriprep/re...,NaN,NaN,Unclassified error,"INFO: fuse2fs not found, will not be able t..."

In [11]:
df_err2 = df_err.query('detail != "INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems"')

In [18]:
df_err3 = df_err2.query('detail != "Traceback (most recent call last):"')

In [19]:
df_err3['file'].value_counts()

file
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI941S5193/log_5881951_72.out     2
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI941S5124/log_5881951_71.out     2
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI941S4376/log_5881951_70.out     2
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI941S4365/log_5881951_69.out     2
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI141S4160/log_5885943_469.out    2
                                                                                                        ..
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI168S6413/log_5881951_12.out     1
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI002S1280/log_5876898_6.out      1
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI002S1261/log_5876898_5.out      1
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI002S0413/log_5876898_1.out      1
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI941S6080/log_5881951_79.out     1
Name: count, Length: 424, dtype: int64

In [20]:
df_err3[df_err3['file'].str.contains('sub-ADNI941S5193')]

,source,file,subject,session,category,detail
1813,log,/N/project/statadni/20250922_Saige/fmriprep/re...,sub-ADNI941S5193,ses-M000,Inputs: session has no BOLD,This session directory exists but contains no ...
1814,log,/N/project/statadni/20250922_Saige/fmriprep/re...,sub-ADNI941S5193,ses-M000,Unclassified error,fMRIPrep failed for sub-ADNI941S5193 with exit...

In [24]:
df_err4 = df_err3.query('category != "Unclassified error"')

In [31]:
df_err4.query('detail == "fMRIPrep failed: Traceback (most recent call last):"')

,source,file,subject,session,category,detail
23,log,/N/project/statadni/20250922_Saige/fmriprep/re...,sub-ADNI002S4237,ses-M006,Nipype node crash,fMRIPrep failed: Traceback (most recent call l...
1415,log,/N/project/statadni/20250922_Saige/fmriprep/re...,sub-ADNI127S6147,ses-M000,Nipype node crash,fMRIPrep failed: Traceback (most recent call l...

In [28]:
df_err4['detail'].value_counts()

detail
This session directory exists but contains no BOLD images (filesystem check)    322
Node anat_ref_dimensions failed to run on host x1002c2s7b0n1.                     2
fMRIPrep failed: Traceback (most recent call last):                               2
[WARNING] Citeproc: citation templateflow not found                               2
Node anat_ref_dimensions failed to run on host x1000c7s0b1n0.                     1
Node anat_ref_dimensions failed to run on host x1000c3s5b0n1.                     1
Node anat_ref_dimensions failed to run on host x1001c2s1b1n1.                     1
Node bidssrc failed to run on host x1000c2s3b0n1.                                 1
Node anat_ref_dimensions failed to run on host x1000c2s0b1n1.                     1
Node anat_ref_dimensions failed to run on host x1001c4s2b1n1.                     1
Node anat_ref_dimensions failed to run on host x1000c2s7b0n0.                     1
Node anat_ref_dimensions failed to run on host x1000c5s1b1n0.                     1
Node bidssrc failed to run on host x1000c2s7b0n0.                                 1
Node bidssrc failed to run on host x1001c4s6b0n1.                                 1
Node bidssrc failed to run on host x1000c7s0b1n1.                                 1
Node bidssrc failed to run on host x1002c0s2b1n0.                                 1
error: Cannot allocate memory                                                     1
Name: count, dtype: int64

In [30]:
df_err4.shape

(341, 6)

In [32]:
df_err4['file'].value_counts()

file
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI002S1280/log_5876898_6.out     1
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI002S4237/log_5876898_14.out    1
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI002S4251/log_5876898_15.out    1
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI003S0908/log_5876898_38.out    1
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI003S1074/log_5876898_39.out    1
                                                                                                       ..
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI941S4365/log_5881951_69.out    1
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI941S4376/log_5881951_70.out    1
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI941S5124/log_5881951_71.out    1
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI941S5193/log_5881951_72.out    1
/N/project/statadni/20250922_Saige/fmriprep/results/scripts/logs/sub-ADNI941S6080/log_5881951_79.out    1
Name: count, Length: 341, dtype: int64